### ISSUE TITLE
Cannot run plugin in windows because of "too long command"

### ISSUE THREAD

**Issue by akoval** [mjedynak/pit-idea-plugin#18]
My result command is about 40KB. So it cannot be run on windows. Probably need to support --classPathFile argument to fix such issues

**Comment by sushantchoudhary** [comment]
Can't seem to get it to work on mac either. Using Idea plugin with required classes and and source dir is erroring out saying 
```
Error running 'app-mutated': Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java": error=7, Argument list too long
```

**Comment by ak80** [comment]
I have encountered the same error, and IntelliJ asked me to enable class path file. I still get an error "Filename or extension too long"

**Comment by mjedynak** [comment]
Fixed in 1.4.0

**Comment by raphaeldirksen** [comment]
I'm still getting this error, even with v1.4.0.

At first, this error appears:

```
Error running 'PIT'
	Command line is too long. In order to reduce its length classpath file can be used.
	Would you like to enable classpath file mode for all run configurations of your project?
	Enable
```

After clicking on "Enable", the following Error Message appears:
`Error running 'PIT': Cannot run program "C:\Program Files\Java\jdk1.8.0_60\bin\java.exe": CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang`

**Comment by raphaeldirksen** [comment]
I'm still getting this error, even with v1.4.0.

At first, this error appears:

```
Error running 'PIT'
	Command line is too long. In order to reduce its length classpath file can be used.
	Would you like to enable classpath file mode for all run configurations of your project?
	Enable
```
After clicking on "Enable", the following Error Message appears:
`Error running 'PIT': Cannot run program "C:\Program Files\Java\jdk1.8.0_60\bin\java.exe": CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang`

**Comment by aaronstj** [comment]
I am also getting this error with 1.4.1.  I don't see the "use classpath jar" checkbox isn't appearing in the configurations form, either.

**Comment by njfactor** [comment]
I too am facing the same issue with v1.4.1.

**Comment by yonatanm** [comment]
when I right-click on a Class to run PIT I get the same error. I'm with v1.4.1 on Ubuntu 19.04

**Comment by sakharuta** [comment]
Same for me. 1.4.1

**Comment by d215steinberg** [comment]
Note that this issue has been reopened as https://github.com/mjedynak/pit-idea-plugin/issues/31
